### ISSUE TITLE
Holiday opening hours

### ISSUE THREAD

**Issue by napei** [phoenix344/opening-hours#2]
Saw this and thought it was neat. Was starting to make my own that respects holiday opening hours as custom, once-off dates.

Is this something you're interested in adding?

It would be similar to how google handles exceptions to standard opening hours, for example,

![image](https://user-images.githubusercontent.com/8946502/103323176-c162eb00-4a95-11eb-8c22-86a1495fb449.png)

Checking opening hours for a current day or week would take into account these hours.

These hours would also need to be marked as "non-standard" in the output somehow so that they can be identified by UI or whatever if necessary.
![image](https://user-images.githubusercontent.com/8946502/103323367-a2188d80-4a96-11eb-8561-6cbd19bab651.png)

**Comment by phoenix344** [comment]
I had the same idea. I rejected it, because the library already serves the use-case it was designed for. Holidays or an event timespan (periodically or one-time events for one or multiple days) is better placed in a new module on top of the opening-hours library.

**Comment by napei** [comment]
> I had the same idea. I rejected it, because the library already serves the use-case it was designed for. Holidays or an event timespan (periodically or one-time events for one or multiple days) is better placed in a new module on top of the opening-hours library.

Thanks. I assumed as much. I'm leaning towards using https://github.com/opening-hours/opening_hours.js for my particular use case but it's atrociously large to be used efficiently 😂 

Thanks for the input though.
