### ISSUE TITLE
Times offset by 1 hour

### ISSUE THREAD

**Issue by napei** [phoenix344/opening-hours#3]
Might be related to daylight savings time, but not sure.

```typescript
import {OpeningHours, WeekDays} from '@phoenix344/opening-hours';

const oh = new OpeningHours({
  text: {
    weekDays: [
      'Sunday',
      'Monday',
      'Tuesday',
      'Wednesday',
      'Thursday',
      'Friday',
      'Saturday',
    ],
    closed: 'closed',
    timespanSeparator: ' to ',
  },
  locales: 'en-AU',
  dateTimeFormatOptions: {
    timeZone: 'Australia/Melbourne',
  },
});

oh.add(WeekDays.Monday, '08:00', '12:30');
console.log(oh.toString());
```

Outputs: `Monday 9:00:00 am to 1:30:00 pm` using node `15.x`. I believe this might be a node problem though, with the timezone not set properly or something like that.

**Comment by phoenix344** [comment]
I was under the impression the DST will be handled by timezone/locale. Seems like I was wrong. If you find a solution in the meantime, please make a pull request. I have some spare time in february, so I can look into it.

**Comment by phoenix344** [comment]
It really depends on the host system. In this case nodejs. I guess this is an issue in browsers, too:

> If the host system is configured for daylight saving, the offset will change depending on the date and time that the Date represents and that daylight saving applies.
[Date.getTimezoneOffset](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset)

**Comment by phoenix344** [comment]
**Update:** The timeZone must not be added to the `date.toLocaleString(locales, options)` options, because this is only for visualizing purpose. That's the easy part.
The timeZone problem is still an issue when it comes to `oh.getState()`, `oh.isOpenSoon()`, `oh.isClosedSoon()` and the calculation of the active day.

**Comment by phoenix344** [comment]
Bugfix is published
