### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by r3dm4n** [phoenix344/opening-hours#7]
Is there something like the next open time available ?

**Comment by phoenix344** [comment]
I need to test it through. I believe that the current development branch is stable, but I'm not quite sure. If you have some spare time to write some additional tests and PR it, I would happily review it.

**Comment by phoenix344** [comment]
I installed travis and yeah... need to do some wörk, but not today.

**Comment by phoenix344** [comment]
At the moment no, but it is pretty easy to implement such a feature. I'm currently working on a version 2, but I guess I can make a feature branch that implements it.
